version: "3.9"

volumes:
  pgdata: {}

services:
  quotes:
    image: gersonfaneto/quotes:1.0.0
    container_name: quotes
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
        PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine
    container_name: db
    user: postgres
    environment:
      POSTGRES_DB: quotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
