version: "3.9"

services:
  quotes:
    container_name: quotes
    image: gersonfaneto/quotes:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
        PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:16.0-alpine
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: quotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
