xh post :8080/quotes book="The Two Towers" quote="There is some good in this world, and it’s worth fighting for."
xh post :8080/quotes book="The Little Prince" quote="It is only with the heart that one can see rightly; what is essential is invisible to the eye."
xh post :8080/quotes book="To Kill a Mockingbird" quote="I wanted you to see what real courage is, instead of getting the idea that courage is a man with a gun in his hand. It’s when you know you’re licked before you begin but you begin anyway and you see it through no matter what. You rarely win, but sometimes you do."
xh post :8080/quotes book="Hamlet" quote="This above all: To thine own self be true, And it must follow, as the night the day, Thou canst not then be false to any man.”"
xh post :8080/quotes book="Les Misérables" quote="It is nothing to die; it is dreadful not to live."
